# Generated by Django 2.1.7 on 2019-02-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_posted', models.DateTimeField(auto_now_add=True)),
                ('data_start', models.DateField()),
                ('data_end', models.DateField()),
                ('promotion_message', models.TextField()),
                ('promotion_name', models.CharField(default='Promocja', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50, unique=True)),
                ('data_posted', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('facebook_id', models.IntegerField()),
                ('restaurant_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
    ]
