# Generated by Django 2.1.7 on 2019-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='data_end',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='data_start',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='facebook_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
